const data = {
    levels: {
        beginner: { title: "Principiante", description: "Aprende lo básico de Python", icon: "fa-seedling", color: "green" },
        intermediate: { title: "Intermedio", description: "Profundiza en estructuras y funciones", icon: "fa-code", color: "blue" },
        advanced: { title: "Avanzado", description: "Domina POO y técnicas avanzadas", icon: "fa-rocket", color: "purple" }
    },
    
    topics: [
        { id: 1, title: "Variables y Tipos", level: "beginner", icon: "fa-database", color: "yellow", description: "Almacena y manipula datos en tu programa", tags: ["Tipos", "Datos", "int", "str", "float", "bool"] },
        { id: 2, title: "Operadores", level: "beginner", icon: "fa-calculator", color: "purple", description: "Operaciones matemáticas y lógicas", tags: ["Aritméticos", "Comparación", "Lógicos"] },
        { id: 3, title: "Condicionales", level: "beginner", icon: "fa-code-branch", color: "pink", description: "Toma decisiones en tu código", tags: ["if", "else", "elif", "match"] },
        { id: 4, title: "Bucles FOR", level: "beginner", icon: "fa-redo", color: "yellow", description: "Itera sobre secuencias", tags: ["range", "enumerate", "zip"] },
        { id: 5, title: "Bucles WHILE", level: "beginner", icon: "fa-bolt", color: "purple", description: "Repetición controlada con condiciones", tags: ["break", "continue", "else"] },
        { id: 6, title: "Funciones", level: "beginner", icon: "fa-cogs", color: "pink", description: "Bloques de código reutilizables", tags: ["def", "return", "args", "kwargs"] },
        { id: 7, title: "Listas", level: "intermediate", icon: "fa-list", color: "green", description: "Colecciones ordenadas", tags: ["append", "remove", "sort", "slice"] },
        { id: 8, title: "Tuplas", level: "intermediate", icon: "fa-layer-group", color: "blue", description: "Secuencias inmutables", tags: ["inmutable", "-desempaquetar"] },
        { id: 9, title: "Diccionarios", level: "intermediate", icon: "fa-map", color: "purple", description: "Pares clave-valor", tags: ["keys", "values", "items", "get"] },
        { id: 10, title: "Conjuntos (Sets)", level: "intermediate", icon: "fa-shapes", color: "pink", description: "Colecciones sin duplicados", tags: ["union", "intersection", "difference"] },
        { id: 11, title: "Comprensión de Listas", level: "intermediate", icon: "fa-list-ol", color: "yellow", description: "Sintaxis eficiente para crear listas", tags: ["list comprehension", "dict comprehension"] },
        { id: 12, title: "Módulos y Paquetes", level: "intermediate", icon: "fa-box", color: "green", description: "Organiza y reutiliza código", tags: ["import", "from", "pip", "venv"] },
        { id: 13, title: "POO - Clases", level: "advanced", icon: "fa-class", color: "purple", description: "Programación orientada a objetos", tags: ["class", "__init__", "self", "objeto"] },
        { id: 14, title: "POO - Herencia", level: "advanced", icon: "fa-sitemap", color: "blue", description: "Reutilización de clases", tags: ["extends", "super", "polimorfismo"] },
        { id: 15, title: "POO - Encapsulamiento", level: "advanced", icon: "fa-lock", color: "pink", description: "Protección de datos", tags: ["private", "protected", "property"] },
        { id: 16, title: "Excepciones", level: "advanced", icon: "fa-exclamation-triangle", color: "yellow", description: "Manejo de errores", tags: ["try", "except", "finally", "raise"] },
        { id: 17, title: "Archivos", level: "advanced", icon: "fa-file-code", color: "green", description: "Lectura y escritura de archivos", tags: ["open", "read", "write", "with"] },
        { id: 18, title: "Decoradores", level: "advanced", icon: "fa-star", color: "purple", description: "Modificar comportamiento de funciones", tags: ["@decorator", "wrapper", "functools"] },
        { id: 19, title: "Generadores", level: "advanced", icon: "fa-sync-alt", color: "blue", description: "Iteradores eficientes", tags: ["yield", "next", "StopIteration"] },
        { id: 20, title: "Regex", level: "advanced", icon: "fa-search", color: "pink", description: "Expresiones regulares", tags: ["re", "match", "search", "findall"] }
    ],
    
    tabs: ["variables", "operadores", "condicionales", "for", "while", "funciones", "listas", "tuplas", "diccionarios", "sets", "comprehension", "modulos", "poo", "excepciones", "archivos", "decoradores", "generadores", "regex"],
    
    syntaxHighlight: {
        keywords: ["def", "class", "if", "elif", "else", "for", "while", "try", "except", "finally", "with", "as", "import", "from", "return", "yield", "raise", "pass", "break", "continue", "and", "or", "not", "in", "is", "lambda", "True", "False", "None", "global", "nonlocal", "assert", "del"],
        functions: ["print", "len", "range", "int", "str", "float", "bool", "list", "dict", "set", "tuple", "type", "input", "open", "sum", "min", "max", "abs", "round", "sorted", "reversed", "enumerate", "zip", "map", "filter", "any", "all", "isinstance", "hasattr", "getattr", "setattr", "delattr", "callable", "id", "dir", "vars", "help"],
        builtins: ["__init__", "__str__", "__repr__", "__len__", "__getitem__", "__setitem__", "__delitem__", "__contains__", "__iter__", "__next__", "__enter__", "__exit__", "__add__", "__sub__", "__mul__", "__div__", "__eq__", "__ne__", "__lt__", "__le__", "__gt__", "__ge__", "__call__"]
    },
    
    codeExamples: {
        variables: [
            { title: "Declaración de Variables", filename: "variables.py", level: "beginner", code: "# Variables en Python\n# No necesitas especificar el tipo\n\nnombre = \"Carlos\"        # str (cadena)\nedad = 25              # int (entero)\naltura = 1.75          # float (decimal)\nes_estudiante = True      # bool (booleano)\n\n# Mostrar valores\nprint(f\"Hola, me llamo {nombre}\")\nprint(f\"Tengo {edad} años\")\nprint(f\"Mido {altura} metros\")\nprint(f\"¿Es estudiante? {es_estudiante}\")\n\n# Ver tipo de dato\nprint(type(nombre))\nprint(type(edad))\nprint(type(altura))" },
            { title: "Conversión de Tipos", filename: "conversion.py", level: "beginner", code: "# Casting (conversión de tipos)\n\n# De string a número\nnumero = int(\"42\")\nprecio = float(\"19.99\")\nprint(numero, type(numero))\nprint(precio, type(precio))\n\n# De número a string\nedad = 25\nprint(\"Tengo \" + str(edad) + \" años\")\n\n# Booleanos\nprint(int(True))    # 1\nprint(int(False))   # 0\nprint(bool(1))      # True\nprint(bool(0))       # False\nprint(bool(\"\"))      # False (string vacío)\nprint(bool(\"hola\"))  # True" },
            { title: "Variables Múltiples", filename: "multiple.py", level: "beginner", code: "# Asignación múltiple\nx, y, z = 1, 2, 3\nprint(x, y, z)\n\n# Mismo valor\na = b = c = 0\nprint(a, b, c)\n\n# Intercambio\nx, y = 10, 20\nx, y = y, x  # Sin variable temporal\nprint(x, y)" },
            { title: "Constantes", filename: "constants.py", level: "beginner", code: "# Python no tiene constantes reales\n# Por convención, mayúsculas\n\nPI = 3.14159\nGRAVEDAD = 9.81\nMAXIMO = 100\n\nprint(f\"PI: {PI}\")\nprint(f\"Gravedad: {GRAVEDAD} m/s²\")\n\n# Intentar modificar (funciona, pero mala práctica)\n# PI = 3.14  # ¡No hagas esto!" }
        ],
        operadores: [
            { title: "Operadores Aritméticos", filename: "arithmetic.py", level: "beginner", code: "a, b = 10, 3\n\nprint(f\"a = {a}, b = {b}\")\nprint(f\"Suma: {a + b}\")           # 13\nprint(f\"Resta: {a - b}\")          # 7\nprint(f\"Multiplicación: {a * b}\") # 30\nprint(f\"División: {a / b}\")      # 3.333...\nprint(f\"División entera: {a // b}\")  # 3\nprint(f\"Módulo: {a % b}\")         # 1\nprint(f\"Potencia: {a ** b}\")      # 1000" },
            { title: "Operadores de Comparación", filename: "comparison.py", level: "beginner", code: "a, b = 5, 10\n\nprint(a == b)   # False (igual)\nprint(a != b)   # True (diferente)\nprint(a < b)    # True (menor)\nprint(a <= b)   # True (menor o igual)\nprint(a > b)    # False (mayor)\nprint(a >= b)   # False (mayor o igual)\n\n# Comparaciones encadenadas\nx = 5\nprint(0 <= x <= 10)  # True" },
            { title: "Operadores Lógicos", filename: "logical.py", level: "beginner", code: "a, b = True, False\n\n# and - ambos True\nprint(True and True)   # True\nprint(True and False)  # False\n\n# or - al menos uno True\nprint(True or False)   # True\nprint(False or False) # False\n\n# not - negación\nprint(not True)   # False\nprint(not False)  # True\n\n# short-circuit evaluation\nedad = 20\ntiene_entrada = True\n\nif edad >= 18 and tiene_entrada:\n    print(\"Puedes entrar\")" },
            { title: "Operadores de Identidad", filename: "identity.py", level: "intermediate", code: "# is vs ==\n# == compara valor\n# is compara identidad (mismo objeto en memoria)\n\nlista1 = [1, 2, 3]\nlista2 = [1, 2, 3]\nlista3 = lista1\n\nprint(lista1 == lista2)  # True (mismo contenido)\nprint(lista1 is lista2)  # False (distintos objetos)\nprint(lista1 is lista3)  # True (mismo objeto)\n\n# Usar is con None\nx = None\nprint(x is None)    # True\nprint(x is not None) # False" },
            { title: "Operadores de Pertenencia", filename: "membership.py", level: "intermediate", code: "# in y not in\n\nfrutas = [\"manzana\", \"pera\", \"uva\"]\nprint(\"manzana\" in frutas)    # True\nprint(\"banano\" in frutas)   # False\n\n# En strings\ntexto = \"Hola mundo\"\nprint(\"Hola\" in texto)    # True\nprint(\"Python\" in texto)   # False\n\n# En diccionarios (solo claves)\npersona = {\"nombre\": \"Carlos\", \"edad\": 25}\nprint(\"nombre\" in persona)   # True\nprint(\"ciudad\" in persona)   # False" }
        ],
        condicionales: [
            { title: "If - Else Básico", filename: "if_else.py", level: "beginner", code: "# Condicional básico\nedad = 20\n\nif edad >= 18:\n    print(\"Eres mayor de edad\")\nelse:\n    print(\"Eres menor de edad\")\n\n# Con elif\nnota = 75\n\nif nota >= 70:\n    print(\"Aprobado - Excelente\")\nelif nota >= 60:\n    print(\"Aprobado - Bueno\")\nelif nota >= 50:\n    print(\"Aprobado - Aceptable\")\nelse:\n    print(\"Reprobado\")" },
            { title: "Operadores Lógicos", filename: "logical_if.py", level: "beginner", code: "edad = 20\ntiene_entrada = True\n\n# and\nif edad >= 18 and tiene_entrada:\n    print(\"Puedes entrar\")\n\n# or\nif edad < 18 or not tiene_entrada:\n    print(\"No puedes entrar\")\n\n# not\nif not tiene_entrada:\n    print(\"Necesitas entrada\")" },
            { title: "Match (Python 3.10+)", filename: "match.py", level: "intermediate", code: "# Match instead of switch\n\ndef HTTP(status):\n    match status:\n        case 200:\n            return \"OK\"\n        case 404:\n            return \"Not Found\"\n        case 500:\n            return \"Server Error\"\n        case _:\n            return \"Unknown\"\n\nprint(HTTP(200))\nprint(HTTP(404))\n\n# Con patrones\ndef describe(punto):\n    match punto:\n        case (0, 0):\n            return \"Origen\"\n        case (x, 0):\n            return f\"Eje X: {x}\"\n        case (0, y):\n            return f\"Eje Y: {y}\"\n        case (x, y):\n            return f\"Punto ({x}, {y})\"\n\nprint(describe((0, 0)))\nprint(describe((5, 0)))" },
            { title: " Ternary Operator", filename: "ternary.py", level: "intermediate", code: "# Operador ternario\nedad = 20\n\n# formula: valor_si_true if condicion else valor_si_false\nresultado = \"mayor\" if edad >= 18 else \"menor\"\nprint(resultado)\n\n# Anidado\nnota = 85\ncalificacion = \"A\" if nota >= 90 else \"B\" if nota >= 80 else \"C\" if nota >= 70 else \"F\"\nprint(calificacion)\n\n# Con listas\nnumeros = [1, 2, 3, 4, 5]\npares = [n for n in numeros if n % 2 == 0]\nprint(pares)" }
        ],
        for: [
            { title: "For Básico", filename: "for_basico.py", level: "beginner", code: "# For básico con range\nprint(\"Range(5):\")\nfor i in range(5):\n    print(i)  # 0, 1, 2, 3, 4\n\n# Range con inicio y fin\nprint(\"\\nRange(2, 6):\")\nfor i in range(2, 6):\n    print(i)  # 2, 3, 4, 5\n\n# Range con paso\nprint(\"\\nRange(0, 10, 2):\")\nfor i in range(0, 10, 2):\n    print(i)  # 0, 2, 4, 6, 8\n\n# Iterar lista\nnombres = [\"Ana\", \"Luis\", \"Maria\"]\nfor nombre in nombres:\n    print(f\"Hola {nombre}\")" },
            { title: "Enumerate", filename: "enumerate.py", level: "beginner", code: "# enumerate - obtiene índice y valor\nfrutas = [\"manzana\", \"banano\", \"uva\"]\n\nfor i, fruta in enumerate(frutas):\n    print(f\"{i}: {fruta}\")\n\n# Con inicio customizado\nfor i, fruta in enumerate(frutas, 1):\n    print(f\"{i}. {fruta}\")\n\n# Enumerate con lista de tuplas\nnumeros = [10, 20, 30]\nfor i, num in enumerate(numeros):\n    print(f\"Índice {i}: {num} (doble: {num*2})\")" },
            { title: "Zip", filename: "zip.py", level: "intermediate", code: "# zip - iterar múltiples listas\nnombres = [\"Ana\", \"Luis\", \"Maria\"]\nnotas = [85, 90, 78]\n\nfor nombre, nota in zip(nombres, notas):\n    print(f\"{nombre}: {nota}\")\n\n# Combinar con enumerate\nfor i, (nombre, nota) in enumerate(zip(nombres, notas)):\n    print(f\"{i+1}. {nombre}: {nota}\")\n\n# Convertir a diccionario\ndiccionario = dict(zip(nombres, notas))\nprint(diccionario)" },
            { title: "Iterar Diccionarios", filename: "for_dict.py", level: "intermediate", code: "persona = {\"nombre\": \"Carlos\", \"edad\": 25, \"ciudad\": \"Madrid\"}\n\n# Iterar claves\nfor clave in persona:\n    print(clave)\n\n# Iterar valores\nfor valor in persona.values():\n    print(valor)\n\n# Iterar pares (clave, valor)\nfor clave, valor in persona.items():\n    print(f\"{clave}: {valor}\")" },
            { title: "For con Else", filename: "for_else.py", level: "intermediate", code: "# else en for se ejecuta al terminar\nfor i in range(3):\n    print(i)\nelse:\n    print(\"Bucle completado\")\n\n# Útil para búsqueda\nnumeros = [2, 4, 6, 8, 10]\n\nfor n in numeros:\n    if n == 7:\n        print(\"Encontrado!\")\n        break\nelse:\n    print(\"No encontrado\")" }
        ],
        while: [
            { title: "While Básico", filename: "while.py", level: "beginner", code: "# While básico\ncontador = 0\n\nwhile contador < 5:\n    print(contador)\n    contador += 1\n\nprint(\"Fin del bucle\")\n\n# While con condición\ncontraseña = \"\"\nwhile contraseña != \"python\":\n    contraseña = input(\"Contraseña: \")\n    if contraseña != \"python\":\n        print(\"Incorrecto\")\nprint(\"¡Correcto!\")" },
            { title: "Break y Continue", filename: "break_continue.py", level: "beginner", code: "# break - sale del bucle\nfor i in range(10):\n    if i == 3:\n        break\n    print(i)\n\nprint(\"---\")\n\n# continue - salta la iteración\nfor i in range(5):\n    if i == 2:\n        continue\n    print(i)\n\n# Ejemplo práctico: buscar en lista\nnumeros = [1, 2, 3, 4, 5]\nbuscado = 3\nfor n in numeros:\n    if n == buscado:\n        print(f\"Encontrado: {n}\")\n        break\nelse:\n    print(\"No encontrado\")" },
            { title: "While True con Break", filename: "while_true.py", level: "intermediate", code: "# While True con BREAK\nwhile True:\n    opcion = input(\"1. Salir, 2. Continuar: \")\n    \n    if opcion == \"1\":\n        print(\"Saliendo...\")\n        break\n    elif opcion == \"2\":\n        print(\"Continuando...\")\n    else:\n        print(\"Opción inválida\")\n\n# Con banderas (flags)\nsecreto = 42\nintentos = 0\nencontrado = False\n\nwhile intentos < 3:\n    intento = int(input(\"Adivina: \"))\n    intentos += 1\n    \n    if intento == secreto:\n        encontrado = True\n        break\n    \n    if intento < secreto:\n        print(\"Mayor\")\n    else:\n        print(\"Menor\")\n\nif encontrado:\n    print(f\"¡Acertaste en {intentos} intentos!\")\nelse:\n    print(\"Perdiste\")" }
        ],
        funciones: [
            { title: "Funciones Básicas", filename: "funciones.py", level: "beginner", code: "# Definir función\ndef saludar(nombre):\n    return f\"Hola {nombre}!\"\n\nprint(saludar(\"Carlos\"))\n\n# Parámetro con valor por defecto\ndef saludar(nombre=\"Amigo\"):\n    return f\"Hola {nombre}!\"\n\nprint(saludar())\nprint(saludar(\"Ana\"))\n\n# Sin return (None)\ndef greet(nombre):\n    print(f\"Hola {nombre}\")\n\nresultado = greet(\"Mundo\")\nprint(resultado)  # None" },
            { title: "Return Múltiple", filename: "return.py", level: "beginner", code: "# Return múltiple (tupla)\ndef operaciones(a, b):\n    return a + b, a - b, a * b, a / b\n\nresultado = operaciones(10, 5)\nprint(resultado)  # (15, 5, 50, 2.0)\n\n# Desempaquetar\nsuma, resta, producto, division = operaciones(10, 5)\nprint(f\"Suma: {suma}\")\nprint(f\"Resta: {resta}\")\n\n# Return temprano\ndef encontrar(lista, objetivo):\n    for i, valor in enumerate(lista):\n        if valor == objetivo:\n            return i\n    return -1\n\nprint(encontrar([1,2,3], 2))" },
            { title: "*args y **kwargs", filename: "args_kwargs.py", level: "intermediate", code: "# *args - argumentos variables\ndef suma(*numeros):\n    print(numeros)\n    return sum(numeros)\n\nprint(suma(1, 2, 3))\nprint(suma(1, 2, 3, 4, 5))\n\n# **kwargs - argumentos con nombre\ndef información(**datos):\n    print(datos)\n    for clave, valor in datos.items():\n        print(f\"{clave}: {valor}\")\n\ninformación(nombre=\"Carlos\", edad=25)\n\n# Combinar\ndef completo(req, *args, **kwargs):\n    print(f\"Requerido: {req}\")\n    print(f\"Args: {args}\")\n    print(f\"Kwargs: {kwargs}\")\n\ncompleto(\"importante\", 1, 2, 3, nombre=\"Carlos\")" },
            { title: "Lambda", filename: "lambda.py", level: "intermediate", code: "# Lambda - funciones anónimas\ncuadrado = lambda x: x ** 2\nprint(cuadrado(5))\n\n# Lambda con múltiples argumentos\nsuma = lambda a, b: a + b\nprint(suma(3, 5))\n\n# Con funciones built-in\nnumeros = [1, 2, 3, 4, 5]\npares = list(filter(lambda x: x % 2 == 0, numeros))\nprint(pares)\n\nduplos = list(map(lambda x: x * 2, numeros))\nprint(duplos)\n\n# Con sorted\npalabras = [\"banana\", \"manzana\", \"uva\"]\npalabras.sort(key=lambda x: len(x))\nprint(palabras)" },
            { title: "Funciones Anidadas", filename: "nested.py", level: "intermediate", code: "# Funciones anidadas\ndef externo():\n    print(\"Externo\")\n    \n    def interno():\n        print(\"Interno\")\n    \n    interno()\n\nexterno()\n\n# Closure\ndef multiplicar(por):\n    def multipli(num):\n        return num * por\n    return multipli\n\nduplicar = multiplicar(2)\ntriplicar = multiplicar(3)\n\nprint(duplicar(5))   # 10\nprint(triplicar(5))  # 15\n\n# Ejemplo práctico\ndef crear_contador():\n    contador = 0\n    def incrementar():\n        nonlocal contador\n        contador += 1\n        return contador\n    return incrementar\n\ncontar = crear_contador()\nprint(contar())  # 1\nprint(contar())  # 2\nprint(contar())  # 3" }
        ],
        listas: [
            { title: "Listas Básicas", filename: "listas.py", level: "beginner", code: "# Listas\nfrutas = [\"manzana\", \"pera\", \"uva\"]\nprint(frutas[0])    # primera\nprint(frutas[-1])   # última\n\n# Modificar\nfrutas[0] = \"banano\"\nprint(frutas)\n\n# Agregar\nfrutas.append(\"naranja\")\nfrutas.insert(1, \"sandía\")\nprint(frutas)\n\n# Eliminar\nfrutas.pop()          # último\nfrutas.remove(\"pera\")\n# del frutas[0]\nprint(frutas)" },
            { title: "Métodos de Lista", filename: "metodos.py", level: "beginner", code: "numeros = [3, 1, 4, 1, 5, 9, 2, 6]\n\n# Ordenar\nnumeros.sort()\nprint(numeros)\n\n# Ordenar inverso\nnumeros.sort(reverse=True)\nprint(numeros)\n\n# Inverso (no modifica)\nnumeros2 = [1, 2, 3]\nnumeros2.reverse()\nprint(numeros2)\n\n# Métodos de conteo\nprint(numeros.count(1))\nprint(numeros.index(5))\n\n# Extender\nlista1 = [1, 2]\nlista2 = [3, 4]\nlista1.extend(lista2)\nprint(lista1)" },
            { title: "Slicing", filename: "slicing.py", level: "beginner", code: "# Slicing - obtener sublistas\nnumeros = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n\nprint(numeros[2:5])    # [2, 3, 4]\nprint(numeros[:3])     # [0, 1, 2]\nprint(numeros[5:])     # [5, 6, 7, 8, 9]\nprint(numeros[::2])    # elementos pares\nprint(numeros[::-1])   # inverso\n\n# Asignar con slicing\nnumeros[1:3] = [20, 30]\nprint(numeros)" },
            { title: "Listas por Comprensión", filename: "list_comp.py", level: "beginner", code: "# Lista por comprensión\ncuadrados = [x**2 for x in range(5)]\nprint(cuadrados)\n\n# Con condición\npares = [x for x in range(10) if x % 2 == 0]\nprint(pares)\n\n# Anidado\nmatriz = [[j for j in range(3)] for i in range(3)]\nprint(matriz)\n\n# Ejemplo práctico\npalabras = [\"Hola\", \"Mundo\", \"Python\", \"Guía\"]\npalabras_largas = [p for p in palabras if len(p) > 4]\nprint(palabras_largas)" },
            { title: "Copiar Listas", filename: "copy.py", level: "intermediate", code: "# Copiar listas - cuidado!\nlista1 = [1, 2, 3]\nlista2 = lista1  # Misma referencia!\nlista2[0] = 99\nprint(lista1)  # [99, 2, 3] - también cambió\n\n# Formas correctas\nlista1 = [1, 2, 3]\n\n# Copia simple (para objetos inmutables)\nlista2 = lista1.copy()\nlista2 = list(lista1)\nlista2 = lista1[:]\n\n# Copia profunda (para listas anidadas)\nimport copy\nlista1 = [[1, 2], [3, 4]]\nlista2 = copy.deepcopy(lista1)" }
        ],
        tuplas: [
            { title: "Tuplas Básicas", filename: "tuplas.py", level: "intermediate", code: "# Tuplas - inmutables\npunto = (10, 20)\nprint(punto[0])   # 10\nprint(punto[-1])    # 20\n\n# unpack\nx, y = punto\nprint(f\"x: {x}, y: {y}\")\n\n# Tupla de un elemento\ntupla = (1,)  # Necesita coma!\nprint(type(tupla))\n\n# Múltiple retorno (funciones)\ndef minmax(numeros):\n    return min(numeros), max(numeros)\n\nresultado = minmax([1, 2, 3, 4, 5])\nprint(resultado)" },
            { title: "Tuplas vs Listas", filename: "tuple_vs_list.py", level: "intermediate", code: "# Tuplas son inmutables (más eficientes)\nimport sys\n\nlista = [1, 2, 3, 4, 5]\ntupla = (1, 2, 3, 4, 5)\n\nprint(sys.getsizeof(lista))  # mayor\nprint(sys.getsizeof(tupla))  # menor\n\n#namedtuple\nfrom collections import namedtuple\n\nPersona = namedtuple(\"Persona\", [\"nombre\", \"edad\"])\ncarlos = Persona(\"Carlos\", 25)\n\nprint(carlos.nombre)\nprint(carlos.edad)\nprint(carlos)" }
        ],
        diccionarios: [
            { title: "Diccionarios Básicos", filename: "diccionarios.py", level: "intermediate", code: "# Diccionarios\npersona = {\n    \"nombre\": \"Carlos\",\n    \"edad\": 25,\n    \"ciudad\": \"Madrid\"\n}\n\n# Acceder\nprint(persona[\"nombre\"])\nprint(persona.get(\"edad\"))\nprint(persona.get(\"telefono\", \"No encontrado\"))\n\n# Modificar\npersona[\"edad\"] = 26\npersona[\"telefono\"] = \"123456789\"\nprint(persona)\n\n# Eliminar\ndel persona[\"ciudad\"]\n# persona.pop(\"ciudad\")\nprint(persona)" },
            { title: "Métodos de Diccionario", filename: "dict_metodos.py", level: "intermediate", code: "persona = {\"nombre\": \"Carlos\", \"edad\": 25, \"ciudad\": \"Madrid\"}\n\n# Keys, values, items\nprint(persona.keys())\nprint(persona.values())\nprint(persona.items())\n\n# Iterar\nfor clave in persona:\n    print(clave)\n\nfor clave, valor in persona.items():\n    print(f\"{clave}: {valor}\")\n\n# Update\npersona2 = {\"pais\": \"España\", \"email\": \"carlos@mail.com\"}\npersona.update(persona2)\nprint(persona)" },
            { title: "Diccionario por Comprensión", filename: "dict_comp.py", level: "intermediate", code: "# Diccionario por comprensión\ncuadrados = {x: x**2 for x in range(5)}\nprint(cuadrados)\n\n# Filtrar\nnumeros = {\"a\": 1, \"b\": 2, \"c\": 3, \"d\": 4}\nfiltrado = {k: v for k, v in numeros.items() if v > 2}\nprint(filtrado)\n\n# Invertir\noriginal = {\"a\": 1, \"b\": 2}\ninvertido = {v: k for k, v in original.items()}\nprint(invertido)\n\n# Combinar con zip\nclaves = [\"nombre\", \"edad\", \"ciudad\"]\nvalores = [\"Carlos\", 25, \"Madrid\"]\ndiccionario = dict(zip(claves, valores))\nprint(diccionario)" },
            { title: "DefaultDict", filename: "defaultdict.py", level: "intermediate", code: "# DefaultDict\nfrom collections import defaultdict\n\n# int default (0)\nconteo = defaultdict(int)\npalabras = [\"hola\", \"mundo\", \"hola\", \"python\", \"hola\"]\n\nfor palabra in palabras:\n    conteo[palabra] += 1\n\nprint(dict(conteo))\n\n# list default\nlista = defaultdict(list)\nlista[\"frutas\"].append(\"manzana\")\nlista[\"frutas\"].append(\"banano\")\nprint(dict(lista))\n\n# set default\nconjuntos = defaultdict(set)\nconjuntos[\"numeros\"].add(1)\nconjuntos[\"numeros\"].add(2)\nprint(dict(conjuntos))" }
        ],
        sets: [
            { title: "Sets Básicos", filename: "sets.py", level: "intermediate", code: "# Sets - sin duplicados\nfrutas = {\"manzana\", \"pera\", \"uva\", \"manzana\"}\nprint(frutas)  # {'manzana', 'pera', 'uva'}\n\n# Operaciones\nset1 = {1, 2, 3, 4}\nset2 = {3, 4, 5, 6}\n\nprint(set1 | set2)  # union {1, 2, 3, 4, 5, 6}\nprint(set1 & set2)  # intersection {3, 4}\nprint(set1 - set2)  # difference {1, 2}\nprint(set1 ^ set2)  # symmetric {1, 2, 5, 6}\n\n# Métodos\nprint(set1.union(set2))\nprint(set1.intersection(set2))" },
            { title: "Operaciones con Sets", filename: "set_operations.py", level: "intermediate", code: "# Verificar pertenencia\nA = {1, 2, 3}\nprint(1 in A)\nprint(5 in A)\n\n# Subset y Superset\nA = {1, 2}\nB = {1, 2, 3}\n\nprint(A.issubset(B))  # True\nprint(B.issuperset(A))  # True\n\n# FrozenSet (inmutable)\nfs = frozenset([1, 2, 3])\n# fs.add(4)  # Error!" }
        ],
        modulos: [
            { title: "Importar Módulos", filename: "import.py", level: "intermediate", code: "# Importar completo\nimport math\n\nprint(math.sqrt(16))\nprint(math.pi)\nprint(math.floor(3.7))\n\n# Importar específico\nfrom math import sqrt, pi\nprint(sqrt(25))\nprint(pi)\n\n# Importar con alias\nimport math as m\nprint(m.sin(m.pi/2))\n\n# Importar todo (no recomendado)\nfrom math import *\nprint(cos(0))" },
            { title: "Módulos Estándar", filename: "standard.py", level: "intermediate", code: "# datetime\nfrom datetime import datetime, timedelta\n\nahora = datetime.now()\nprint(ahora)\nprint(ahora.strftime(\"%Y-%m-%d\"))\n\n# random\nimport random\nprint(random.randint(1, 10))\nprint(random.choice([\"a\", \"b\", \"c\"]))\nprint(random.shuffle([1, 2, 3]))\n\n# json\nimport json\ndata = {\"nombre\": \"Carlos\"}\njson_str = json.dumps(data)\nprint(json.loads(json_str))\n\n# os\nimport os\nprint(os.getcwd())\nprint(os.listdir(\".\"))" },
            { title: "Crear Módulo", filename: "modulo.py", level: "intermediate", code: "# modulo.py (archivo)\ndef saludar(nombre):\n    return f\"Hola {nombre}!\"\n\n# main.py\nfrom modulo import saludar\nprint(saludar(\"Carlos\"))\n\n# __init__.py para paquete\n# mi_paquete/\n#   __init__.py\n#   modulo1.py\n#   modulo2.py" }
        ],
        poo: [
            { title: "Clases y Objetos", filename: "clases.py", level: "advanced", code: "# Definir clase\nclass Persona:\n    # Constructor\n    def __init__(self, nombre, edad):\n        self.nombre = nombre\n        self.edad = edad\n    \n    # Método\n    def saludar(self):\n        return f\"Hola, soy {self.nombre}\"\n    \n    def __str__(self):\n        return f\"Persona({self.nombre}, {self.edad})\"\n\n# Crear objeto\npersona = Persona(\"Carlos\", 25)\nprint(persona.saludar())\nprint(persona.nombre)\nprint(persona)" },
            { title: "Herencia", filename: "herencia.py", level: "advanced", code: "# Clase base\nclass Animal:\n    def __init__(self, nombre):\n        self.nombre = nombre\n    \n    def speak(self):\n        return \"...\"\n\n# Clase derivada\nclass Perro(Animal):\n    def speak(self):\n        return \"Guau!\"\n\nclass Gato(Animal):\n    def speak(self):\n        return \"Miau!\"\n\nperro = Perro(\"Fido\")\nprint(perro.nombre)\nprint(perro.speak())\n\n# Herencia múltiple\nclass Volador:\n    def volar(self):\n        return \"Volando\"\n\nclass Pato(Animal, Volador):\n    def speak(self):\n        return \"Cuac!\"\n\npato = Pato(\"Donald\")\nprint(pato.speak())\nprint(pato.volar())" },
            { title: "Super y Polimorfismo", filename: "super.py", level: "advanced", code: "# Super\nclass Persona:\n    def __init__(self, nombre, edad):\n        self.nombre = nombre\n        self.edad = edad\n\nclass Empleado(Persona):\n    def __init__(self, nombre, edad, salario):\n        super().__init__(nombre, edad)\n        self.salario = salario\n\n# Polimorfismo\nclass Animal:\n    def hacer_sonido(self):\n        pass\n\nclass Perro(Animal):\n    def hacer_sonido(self):\n        return \"Guau\"\n\nclass Gato(Animal):\n    def hacer_sonido(self):\n        return \"Miau\"\n\n\nanimales = [Perro(), Gato()]\nfor animal in animales:\n    print(animal.hacer_sonido())" },
            { title: "Encapsulamiento", filename: "encapsulamiento.py", level: "advanced", code: "# Encapsulamiento\nclass Cuenta:\n    def __init__(self, saldo):\n        self.__saldo = saldo  # privado (name mangling)\n    \n    @property\n    def saldo(self):\n        return self.__saldo\n    \n    @saldo.setter\n    def saldo(self, valor):\n        if valor >= 0:\n            self.__saldo = valor\n        else:\n            raise ValueError(\"Saldo no puede ser negativo\")\n\ncuenta = Cuenta(1000)\nprint(cuenta.saldo)\ncuenta.saldo = 2000\nprint(cuenta.saldo)" },
            { title: "Métodos de Clase", filename: "metodos_clase.py", level: "advanced", code: "# @classmethod\nclass Persona:\n    contador = 0\n    \n    def __init__(self, nombre):\n        self.nombre = nombre\n        Persona.contador += 1\n    \n    @classmethod\n    def desde_string(cls, s):\n        nombre = s.split(\":\")[1]\n        return cls(nombre)\n\n# @staticmethod\nclass Calculadora:\n    @staticmethod\n    def sumar(a, b):\n        return a + b\n\nprint(Persona.contador)\np = Persona(\"Carlos\")\nprint(Persona.contador)\nprint(Calculadora.sumar(2, 3))" },
            { title: "Clases Abstractas", filename: "abstract.py", level: "advanced", code: "from abc import ABC, abstractmethod\n\nclass Figura(ABC):\n    @abstractmethod\n    def area(self):\n        pass\n    \n    @abstractmethod\n    def perimetro(self):\n        pass\n\nclass Rectangulo(Figura):\n    def __init__(self, ancho, alto):\n        self.ancho = ancho\n        self.alto = alto\n    \n    def area(self):\n        return self.ancho * self.alto\n    \n    def perimetro(self):\n        return 2 * (self.ancho + self.alto)\n\nr = Rectangulo(5, 3)\nprint(r.area())\nprint(r.perimetro())" }
        ],
        excepciones: [
            { title: "Try - Except", filename: "try_except.py", level: "advanced", code: "# Try - Except básico\ntry:\n    resultado = 10 / 0\nexcept ZeroDivisionError:\n    print(\"No se puede dividir por cero\")\n\n# Multiples except\ntry:\n    x = int(\"hola\")\nexcept ValueError:\n    print(\"Valor inválido\")\nexcept ZeroDivisionError:\n    print(\"División por cero\")\n\n# Capturar todas\ntry:\n    x = 1 / 0\nexcept Exception as e:\n    print(f\"Error: {e}\")" },
            { title: "Try - Except - Else", filename: "try_else.py", level: "advanced", code: "# Else se ejecuta si no hay error\ntry:\n    x = int(\"10\")\nexcept ValueError:\n    print(\"Error\")\nelse:\n    print(f\"Conversión exitosa: {x}\")\n    \n# Finally siempre se ejecuta\ntry:\n    archivo = open(\"archivo.txt\", \"r\")\n    contenido = archivo.read()\nfinally:\n    archivo.close()\n    print(\"Archivo cerrado\")\n\n# With (recomendado)\nwith open(\"archivo.txt\") as archivo:\n    contenido = archivo.read()" },
            { title: "Raise", filename: "raise.py", level: "advanced", code: "# Raise - lanzar excepción\ndef división(a, b):\n    if b == 0:\n        raise ValueError(\"Divisor no puede ser cero\")\n    return a / b\n\ntry:\n    resultado = división(10, 0)\nexcept ValueError as e:\n    print(e)\n\n# Excepciones personalizadas\nclass MiError(Exception):\n    pass\n\ndef validar(edad):\n    if edad < 0:\n        raise MiError(\"Edad no puede ser negativa\")\n    return \"Válido\"\n\ntry:\n    validar(-5)\nexcept MiError as e:\n    print(e)" }
        ],
        archivos: [
            { title: "Leer y Escribir", filename: "archivos.py", level: "advanced", code: "# Escribir\nwith open(\"saludo.txt\", \"w\") as archivo:\n    archivo.write(\"Hola mundo\\n\")\n    archivo.write(\"Segunda línea\")\n\n# Leer\nwith open(\"saludo.txt\", \"r\") as archivo:\n    # contenido = archivo.read()\n    # lineas = archivo.readlines()\n    for linea in archivo:\n        print(linea.strip())\n\n# Append\nwith open(\"saludo.txt\", \"a\") as archivo:\n    archivo.write(\"\\nNueva línea\")" },
            { title: "CSV", filename: "csv.py", level: "advanced", code: "import csv\n\n# Escribir\nwith open(\"datos.csv\", \"w\", newline=\"\") as archivo:\n    escritor = csv.writer(archivo)\n    escritor.writerow([\"Nombre\", \"Edad\"])\n    escritor.writerow([\"Carlos\", 25])\n    escritor.writerow([\"Ana\", 30])\n\n# Leer\nwith open(\"datos.csv\", \"r\") as archivo:\n    lector = csv.reader(archivo)\n    for fila in lector:\n        print(fila)" },
            { title: "JSON", filename: "json_file.py", level: "advanced", code: "import json\n\n# Escribir\ndata = {\"nombre\": \"Carlos\", \"edad\": 25}\nwith open(\"data.json\", \"w\") as archivo:\n    json.dump(data, archivo)\n\n# Leer\nwith open(\"data.json\", \"r\") as archivo:\n    data = json.load(archivo)\n    print(data)" }
        ],
        decoradores: [
            { title: "Decoradores Básicos", filename: "decoradores.py", level: "advanced", code: "# Decorador básico\ndef mi_decorador(funcion):\n    def wrapper(*args, **kwargs):\n        print(\"Antes\")\n        result = funcion(*args, **kwargs)\n        print(\"Después\")\n        return result\n    return wrapper\n\n@mi_decorador\ndef saludar():\n    print(\"Hola!\")\n\nsaludar()\n\n# Con argumentos\ndef temporizador(funcion):\n    import time\n    def wrapper(*args, **kwargs):\n        inicio = time.time()\n        result = funcion(*args, **kwargs)\n        print(f\"Tiempo: {time.time() - inicio}\")\n        return result\n    return wrapper\n\n@temporizador\ndef lento():\n    import time\n    time.sleep(1)\n\nlento()" },
            { title: "Decoradores con Args", filename: "decorador_args.py", level: "advanced", code: "# Decorador con parámetros\ndef repeat(times):\n    def decorator(func):\n        def wrapper(*args, **kwargs):\n            for _ in range(times):\n                result = func(*args, **kwargs)\n            return result\n        return wrapper\n    return decorator\n\n@repeat(times=3)\ndef saludar():\n    print(\"Hola!\")\n\nsaludar()" },
            { title: "Functools Wraps", filename: "wraps.py", level: "advanced", code: "from functools import wraps\n\ndef mi_decorador(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        \"\"\"Documentación del wrapper\"\"\"\n        return func(*args, **kwargs)\n    return wrapper\n\n@mi_decorador\ndef saludar():\n    \"\"\"Saluda al usuario\"\"\"\n    print(\"Hola!\")\n\nprint(saludar.__name__)  # saludar (no wrapper)\nprint(saludar.__doc__)   # Saluda al usuario" }
        ],
        generadores: [
            { title: "Yield", filename: "generadores.py", level: "advanced", code: "# Generador con yield\ndef contar(n):\n    i = 1\n    while i <= n:\n        yield i\n        i += 1\n\nfor num in contar(5):\n    print(num)\n\n# Convertir a lista\nprint(list(contar(3)))\n\n# next\ngen = contar(3)\nprint(next(gen))  # 1\nprint(next(gen))  # 2\nprint(next(gen))  # 3\n# print(next(gen))  # StopIteration" },
            { title: "Generadores vs Listas", filename: "gen_vs_list.py", level: "advanced", code: "# Listas cargan todo en memoria\ndef squares_list(n):\n    return [x**2 for x in range(n)]\n\n# Generadores son lazy (memoria eficiente)\ndef squares_gen(n):\n    for x in range(n):\n        yield x**2\n\nimport sys\n\nlista = squares_list(1000000)\nprint(sys.getsizeof(lista))\n\ngenerador = squares_gen(1000000)\nprint(sys.getsizeof(generador))" },
            { title: "Pipeline de Generadores", filename: "pipeline.py", level: "advanced", code: "# Pipeline de generadores\ndef leer_numeros():\n    for i in range(1, 11):\n        yield i\n\ndef filtrar_pares(gen):\n    for n in gen:\n        if n % 2 == 0:\n            yield n\n\ndef multiplicar(gen, factor):\n    for n in gen:\n        yield n * factor\n\n# chaining\nresultado = multiplicar(filtrar_pares(leer_numeros()), 10)\nprint(list(resultado))" }
        ],
        regex: [
            { title: "Regex Básico", filename: "regex.py", level: "advanced", code: "import re\n\n# search\ntexto = \"MiTEL: 12345678\"\nif re.search(r\"\\\\d{8}\", texto):\n    print(\"Teléfono encontrado\")\n\n# match (inicio)\nif re.match(r\"\\\\w+\", texto):\n    print(\"Empieza con palabra\")\n\n# findall\ntexto = \"Tengo 2 gatos y 3 perros\"\nnumeros = re.findall(r\"\\\\d+\", texto)\nprint(numeros)  # ['2', '3']\n\n# sub (reemplazar)\ntexto = \"Hola   mundo\"\ntexto_limpio = re.sub(r\"\\\\s+\", \" \", texto)\nprint(texto_limpio)" },
            { title: "Regex Avanzado", filename: "regex_avanzado.py", level: "advanced", code: "import re\n\n# Grupos\ntexto = \"Carlos <carlos@correo.com>\"\nmatch = re.search(r\"(\\w+) <(.+@.+)>\", texto)\nif match:\n    print(match.group(1))\n    print(match.group(2))\n\n# Named groups\nmatch = re.search(r\"(?P<nombre>\\\\w+) (?P<correo><.+@.+>)\", texto)\nprint(match.group(\"nombre\"))\nprint(match.group(\"correo\"))\n\n# compile\npatron = re.compile(r\"\\\\d{4}-\\\\d{4}\")\nif patron.match(\"1234-5678\"):\n    print(\"Válido\")" },
            { title: "Validaciones con Regex", filename: "validaciones.py", level: "advanced", code: "import re\n\n# Email\ndef validar_email(email):\n    patron = r\"^[\\\\w.-]+@[\\\\w.-]+\\\\.\\\\w+$\"\n    return re.match(patron, email) is not None\n\n# Teléfono\ndef validar_telefono(tel):\n    patron = r\"^\\\\+?\\\\d{1,3}\\\\\.\\\\d{9,10}$\"\n    return re.match(patron, tel) is not None\n\n# URL\ndef validar_url(url):\n    patron = r\"^https?://[\\\\w.-]+(?:/[\\\\w.-]*)*$\"\n    return re.match(patron, url) is not None\n\nprint(validar_email(\"carlos@correo.com\"))\nprint(validar_telefono(\"+549876543210\"))\nprint(validar_url(\"https://sitio.com\"))" }
        ]
    },
    
    exercises: [
        { level: 1, title: "Hola Mundo", description: "Imprime 'Hola, Mundo!' en pantalla", difficulty: "beginner", category: "basics", tags: ["print"] },
        { level: 2, title: "Calculadora Básica", description: "Crea una calculadora con suma, resta, multiplicación y división", difficulty: "beginner", category: "operators", tags: ["input", "int", "float"] },
        { level: 3, title: "Conversor de Temperatura", description: "Convierte entre Celsius, Fahrenheit y Kelvin", difficulty: "beginner", category: "operators", tags: ["f-strings", "fórmulas"] },
        { level: 4, title: "Par o Impar", description: "Determina si un número es par o impar", difficulty: "beginner", category: "conditionals", tags: ["módulo", "%"] },
        { level: 5, title: "Calculadora de Notas", description: "Calcula promedio y determina aprobación (nota >= 70)", difficulty: "beginner", category: "conditionals", tags: ["if", "elif", "else"] },
        { level: 6, title: "Generador de Tablas", description: "Imprime la tabla de multiplicar de un número", difficulty: "beginner", category: "loops", tags: ["for", "range"] },
        { level: 7, title: "Contador con FOR", description: "Itera y calcula el promedio de una lista", difficulty: "beginner", category: "loops", tags: ["for", "sum"] },
        { level: 8, title: "Validar Contraseña", description: "Valida que la contraseña tenga al menos 8 caracteres", difficulty: "beginner", category: "conditionals", tags: ["len", "if"] },
        { level: 9, title: "Lista Inversa", description: "Invierte una lista sin usar reverse()", difficulty: "intermediate", category: "lists", tags: ["for", "append"] },
        { level: 10, title: "Eliminar Duplicados", description: "Elimina elementos duplicados de una lista", difficulty: "intermediate", category: "lists", tags: ["set"] },
        { level: 11, title: "Ordenar Lista", description: "Implementa bubble sort para ordenar una lista", difficulty: "intermediate", category: "algorithms", tags: ["for", "while"] },
        { level: 12, title: "Contador de Palabras", description: "Cuenta las palabras en un texto", difficulty: "intermediate", category: "strings", tags: ["split", "dict"] },
        { level: 13, title: "FizzBuzz", description: "Imprime fizzbuzz: múltiplos de 3=fizz, 5=buzz, ambos=fizzbuzz", difficulty: "intermediate", category: "conditionals", tags: ["for", "%"] },
        { level: 14, title: "Fibonacci", description: "Genera los primeros N números de Fibonacci", difficulty: "intermediate", category: " algorithms", tags: ["list", "for"] },
        { level: 15, title: "Buscar en Lista", description: "Implementa búsqueda lineal y binaria", difficulty: "intermediate", category: "algorithms", tags: ["for", "while"] },
        { level: 16, title: "Gestión de Productos", description: "Crea un CRUD de productos con diccionario", difficulty: "intermediate", category: "dictionaries", tags: ["dict", "create", "read", "update", "delete"] },
        { level: 17, title: "Calculadora con Funciones", description: "Implementa calculadora usando funciones", difficulty: "intermediate", category: "functions", tags: ["def", "args", "return"] },
        { level: 18, title: "Calculadora con Lambda", description: "Crea calculadora usando lambdas", difficulty: "intermediate", category: "functions", tags: ["lambda"] },
        { level: 19, title: "Clase Persona", description: "Crea una clase Persona con atributos y métodos", difficulty: "advanced", category: "poo", tags: ["class", "__init__", "self"] },
        { level: 20, title: "Herencia Animal", description: "Implementa jerarquía animal con clases", difficulty: "advanced", category: "poo", tags: ["class", "inheritance"] },
        { level: 21, title: "Manejo de Errores", description: "Maneja erros con try/except en operaciones", difficulty: "advanced", category: "exceptions", tags: ["try", "except", "finally"] },
        { level: 22, title: "Leer Archivo CSV", description: "Lee y muestra datos de un archivo CSV", difficulty: "advanced", category: "files", tags: ["csv", "open"] },
        { level: 23, title: "Decorador de Tiempo", description: "Crea decorador para medir tiempo de ejecución", difficulty: "advanced", category: "decorators", tags: ["decorator", "time"] },
        { level: 24, title: "Generador de Números", description: "Crea generador para números pares", difficulty: "advanced", category: "generators", tags: ["yield"] },
        { level: 25, title: "Validación con Regex", description: "Valida emails y teléfonos con regex", difficulty: "advanced", category: "regex", tags: ["re", "match"] }
    ],
    
    quiz: [
        { question: "¿Cómo se declara una variable en Python?", options: ["var nombre = 'Ana'", "nombre = 'Ana'", "let nombre = 'Ana'", "int nombre = 'Ana'"], correct: 1, level: "beginner", category: "variables" },
        { question: "¿Cuál es el tipo de dato de: precio = 19.99?", options: ["int", "str", "float", "bool"], correct: 2, level: "beginner", category: "variables" },
        { question: "¿Qué operador calcula la potencia en Python?", options: ["^", "**", "pow()", "power()"], correct: 1, level: "beginner", category: "operators" },
        { question: "¿Cómo se escribe un comentario en Python?", options: ["// comentario", "# comentario", "/* comentario */", "-- comentario"], correct: 1, level: "beginner", category: "variables" },
        { question: "¿Cuál es el operador 'and' lógico en Python?", options: ["&&", "and", "AND", "&"], correct: 1, level: "beginner", category: "operators" },
        { question: "¿Cómo se define una función en Python?", options: ["function saludar()", "def saludar():", "func saludar()", "void saludar()"], correct: 1, level: "beginner", category: "functions" },
        { question: "¿Qué método agrega un elemento al final de una lista?", options: ["add()", "append()", "push()", "insert()"], correct: 1, level: "beginner", category: "lists" },
        { question: "¿Cómo se accede al último elemento de una lista?", options: ["lista[-1]", "lista[len(lista)]", "lista.last()", "lista(0)"], correct: 0, level: "beginner", category: "lists" },
        { question: "¿Qué palabra clave se usa para crear una clase?", options: ["object", "struct", "class", "new"], correct: 2, level: "beginner", category: "poo" },
        { question: "¿Cómo se crea un diccionario vacío?", options: ["dict = []", "dict = ()", "dict = {}", "dict = dict()"], correct: 2, level: "beginner", category: "dictionaries" },
        { question: "¿Cuál es el operador de división entera?", options: ["/", "//", "%", ":"], correct: 1, level: "beginner", category: "operators" },
        { question: "¿Cómo se hace un bucle FOR del 0 al 4?", options: ["for i in range(5):", "for i in range(1,5):", "for i in 0..5:", "for i = 0 to 5:"], correct: 0, level: "beginner", category: "loops" },
        { question: "¿Qué hace 'break' en un bucle?", options: ["Pausa el bucle", "Sale del bucle", "Continúa siguiente iteración", "Reinicia el bucle"], correct: 1, level: "beginner", category: "loops" },
        { question: "¿Cómo se importa un módulo en Python?", options: ["import nombre", "include nombre", "require nombre", "using nombre"], correct: 0, level: "beginner", category: "modules" },
        { question: "¿Qué función muestra texto en pantalla?", options: ["echo()", "print()", "write()", "display()"], correct: 1, level: "beginner", category: "basics" },
        { question: "¿Cuál es la diferencia entre tupla y lista?", options: ["Las tuplas son más rápidas", "Las tuplas son inmutables", "Las tuplas usan menos memoria", "Todas las anteriores"], correct: 3, level: "intermediate", category: "lists" },
        { question: "¿Qué hace el método .get() en un diccionario?", options: ["Obtiene valor por clave", "Elimina una clave", "Agrega una clave", "Actualiza una clave"], correct: 0, level: "intermediate", category: "dictionaries" },
        { question: "¿Qué operador se usa para membresía en listas?", options: ["contains", "in", "has", "exists"], correct: 1, level: "intermediate", category: "operators" },
        { question: "¿Para qué sirve *args en una función?", options: ["Argumentos por defecto", "Argumentos variables", "Argumentos nominados", "No existe"], correct: 1, level: "intermediate", category: "functions" },
        { question: "¿Qué significa self en una clase?", options: ["Una variable", "La instancia actual", "Una función", "Un parámetro"], correct: 1, level: "intermediate", category: "poo" },
        { question: "¿Cómo se hereda de una clase padre?", options: ["class Hija(Padre):", "class Hija extends Padre:", "class Hija -> Padre:", "class Hija inherits Padre:"], correct: 0, level: "advanced", category: "poo" },
        { question: "¿Qué hace el bloque finally?", options: ["Se ejecuta si hay error", "Siempre se ejecuta", "Se ejecuta si no hay error", "No existe"], correct: 1, level: "advanced", category: "exceptions" },
        { question: "¿Qué es un decorador?", options: ["Una variable", "Una función que modifica otra función", "Una clase", "Un bucle"], correct: 1, level: "advanced", category: "decorators" },
        { question: "¿Qué hace yield en una función?", options: ["Retorna valor", "Crea un generador", "Lanza error", "Termina función"], correct: 1, level: "advanced", category: "generators" },
        { question: "¿Qué expresión regular coincide con un email?", options: ["[a-z]+", "\\\\w+@\\\\w+", "^[\\\\w.-]+@[\\\\w.-]+\\\\.\\\\w+$", ".*@.*"], correct: 2, level: "advanced", category: "regex" }
    ]
};