import {
  Database,
  Type,
  Braces,
  Calculator,
  GitBranch,
  Repeat,
  Zap,
  Cog,
  List,
  Layers,
  Map as MapIcon,
  Shapes,
  ListOrdered,
  Dices,
  Package,
  Boxes,
  CalendarClock,
  BadgeCheck,
  Workflow,
  Globe,
  Box,
  TriangleAlert,
  FileCode,
  Sparkles,
  RefreshCw,
  Regex,
  Sprout,
  Code2,
  Rocket,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const TOPIC_ICONS: Record<string, LucideIcon> = {
  variables: Database,
  strings: Type,
  fstrings: Braces,
  operadores: Calculator,
  condicionales: GitBranch,
  for: Repeat,
  while: Zap,
  funciones: Cog,
  listas: List,
  tuplas: Layers,
  diccionarios: MapIcon,
  sets: Shapes,
  comprehension: ListOrdered,
  random_math: Dices,
  modulos: Package,
  pip_venv: Boxes,
  datetime: CalendarClock,
  typing: BadgeCheck,
  itertools: Workflow,
  json_api: Globe,
  poo: Box,
  excepciones: TriangleAlert,
  archivos: FileCode,
  decoradores: Sparkles,
  generadores: RefreshCw,
  regex: Regex,
};

export const LEVEL_ICONS: Record<string, LucideIcon> = {
  beginner: Sprout,
  intermediate: Code2,
  advanced: Rocket,
};
